// app
export const CHANGE_THEME = 'CHANGE_THEME';

export const SET_EXTENSIONS_LIST = 'SET_EXTENSIONS_LIST';
export const SET_CUR_EXT = 'SET_CUR_EXT';

export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CLOSE_CONNECTING = 'CLOSE_CONNECTING';

export const SET_WALLET_IS_CONNECTED = 'SET_WALLET_IS_CONNECTED';

export const SHOW_ACCOUNT = 'SHOW_ACCOUNT';
export const HIDE_ACCOUNT = 'HIDE_ACCOUNT';

export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';

// wallet
export const SET_WALLET = 'SET_WALLET';
export const SET_PUBKEY = 'SET_PUBKEY';
export const SET_TOKEN_LIST = 'SET_TOKEN_LIST';
export const SET_PAIRS_LIST = 'SET_PAIRS_LIST';
export const SET_LIQUIDITY_LIST = 'SET_LIQUIDITY_LIST';
export const SET_TRANSACTIONS_LIST = 'SET_TRANSACTIONS_LIST';
export const SET_SUBSCRIBE_DATA = 'SET_SUBSCRIBE_DATA';

// Client wallets
export const SHOW_CLIENT_WALLETS_FROM_SELECT = 'SHOW_CLIENT_WALLETS_FROM_SELECT';
export const HIDE_CLIENT_WALLETS_FROM_SELECT = 'HIDE_CLIENT_WALLETS_FROM_SELECT';

// Pool explorer
export const SHOW_POOL_EXPLORER = 'SHOW_POOL_EXPLORER';
export const HIDE_POOL_EXPLORER = 'HIDE_POOL_EXPLORER';


// swap
export const SHOW_SWAP_FROM_SELECT = 'SHOW_SWAP_FROM_SELECT';
export const HIDE_SWAP_FROM_SELECT = 'HIDE_SWAP_FROM_SELECT';

export const SHOW_SWAP_TO_SELECT = 'SHOW_SWAP_TO_SELECT';
export const HIDE_SWAP_TO_SELECT = 'HIDE_SWAP_TO_SELECT';

export const SET_SWAP_FROM_INPUT_VALUE = 'SET_SWAP_FROM_INPUT_VALUE';
export const SET_SWAP_TO_INPUT_VALUE = 'SET_SWAP_TO_INPUT_VALUE';

export const SET_SWAP_FROM_TOKEN = 'SET_SWAP_FROM_TOKEN';
export const SET_SWAP_TO_TOKEN = 'SET_SWAP_TO_TOKEN';

export const SET_SWAP_PAIR_ID = 'SET_SWAP_PAIR_ID';

export const SET_SWAP_ASYNC_IS_WAITING = 'SET_SWAP_ASYNC_IS_WAITING';

export const SET_SWAP_RATE = 'SET_SWAP_RATE';
export const SET_SWAP_FROM_INPUT_VALUE_CHANGE = 'SET_SWAP_FROM_INPUT_VALUE_CHANGE';


// pool
export const SHOW_POOL_FROM_SELECT = 'SHOW_POOL_FROM_SELECT';
export const HIDE_POOL_FROM_SELECT = 'HIDE_POOL_FROM_SELECT';

export const SHOW_POOL_TO_SELECT = 'SHOW_POOL_TO_SELECT';
export const HIDE_POOL_TO_SELECT = 'HIDE_POOL_TO_SELECT';

export const SET_POOL_FROM_INPUT_VALUE = 'SET_POOL_FROM_INPUT_VALUE';
export const SET_POOL_TO_INPUT_VALUE = 'SET_POOL_TO_INPUT_VALUE';

export const SET_POOL_FROM_TOKEN = 'SET_POOL_FROM_TOKEN';
export const SET_POOL_TO_TOKEN = 'SET_POOL_TO_TOKEN';

export const SET_POOL_PAIR_ID = 'SET_POOL_PAIR_ID';

export const SET_POOL_ASYNC_IS_WAITING = 'SET_POOL_ASYNC_IS_WAITING';

export const SET_POOL_RATE = 'SET_POOL_RATE';

//  manage
export const SET_MANAGE_FROM_TOKEN = 'SET_MANAGE_FROM_TOKEN';
export const SET_MANAGE_TO_TOKEN = 'SET_MANAGE_TO_TOKEN';

export const SET_MANAGE_RATE_AB = 'SET_MANAGE_RATE_AB';
export const SET_MANAGE_RATE_BA = 'SET_MANAGE_RATE_BA';

export const SET_MANAGE_PAIR_ID = 'SET_MANAGE_PAIR_ID';

export const SET_MANAGE_BALANCE = 'SET_MANAGE_BALANCE';

export const SET_MANAGE_ASYNC_IS_WAITING = 'SET_MANAGE_ASYNC_IS_WAITING';
