name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Setup key
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          chmod 0700 "$HOME/.ssh/"
          echo "${{ secrets.TEST_KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # Deploy
      - name: Deploy
        
      # run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . /var/www/bt/build/ #root@178.170.47.43:/var/www/bt/build/
      
        name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.test_key }}
      
        run: rsync -e "ssh -i key -o StrictHostKeyChecking=no" . root@178.170.47.43:/var/www/bt/build/
        # working-directory: ./dist


      # - name: Deploy to Server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.DEPLOY_SERVER_HOST }}
      #     port: ${{ secrets.DEPLOY_SERVER_PORT }}
      #     username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
      #     key: ${{ secrets.DEPLOY_SERVER_KEY }}
      #     source: ${{ env.BUILD_SCRIPT_OUTPUT }}
      #     target: ${{ env.DEPLOY_PATH }}/${{ env.BRANCH_NAME }}
      #     strip_components: 1



# name: CI

# on: [push]

# env:
#   DEPLOY_PATH: /var/www/app
#   # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
#   BUILD_SCRIPT: npm run build
#   BUILD_SCRIPT_OUTPUT: dist

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # Делаем checkout текущей ветки
#       - uses: actions/checkout@v2
#       # Устанавливаем Node.JS для сборки приложения
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '14'
#       # Записываем в переменные окружения имя текущей ветки
#       # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
#       - name: Get branch name
#         shell: bash
#         run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g')"
#       # Устанавливаем зависимости для сборки
#       - name: Install Dependencies
#         run: npm i
#       # Собираем приложение
#       - name: Build Appliction
#         run: $BUILD_SCRIPT
#       # Доставляем собранное приложение на сервер
#       - name: Deploy to Server
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.DEPLOY_SERVER_HOST }}
#           port: ${{ secrets.DEPLOY_SERVER_PORT }}
#           username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
#           key: ${{ secrets.DEPLOY_SERVER_KEY }}
#           source: ${{ env.BUILD_SCRIPT_OUTPUT }}
#           target: ${{ env.DEPLOY_PATH }}/${{ env.BRANCH_NAME }}
#           strip_components: 1
#       - name: Print Info
#         run: echo "Deployed at https://${BRANCH_NAME}.app.example.ru/"                  
